export const PENDING_EMAIL_VERIFICATION_KEY = "PENDING_EMAIL_VERIFICATION";
export const PENDING_EMAIL_VERIFICATION_DATA_KEY =
  "PENDING_EMAIL_VERIFICATION_DATA";

export const SIGNUP_OBJECT_KEY = "SIGNUP_OBJECT";
