export const chatData = [
  {
    id: "",
    posts: [""],
    username: "Ableez",
    imageUrl: require("../assets/images/avatars/02.png"),
    message: "Hey whatsup bro🥂🥂✌🏽",
    timestamp: "2024-07-16T08:00:00Z",
    unreadMessages: 1,
    whoSentLastMessage: "Ableez",
  },
  {
    id: "",
    posts: [""],
    username: "Laura",
    imageUrl: require("../assets/images/avatars/01.png"),
    message: "Are you coming over tonight?🌚",
    timestamp: "2024-07-15T20:30:00Z",
    unreadMessages: 0,
    whoSentLastMessage: "you",
  },
  {
    id: "",
    posts: [""],
    username: "Mike",
    imageUrl: require("../assets/images/avatars/04.png"),
    message: "Check out this cool new app! 😎📱",
    timestamp: "2024-07-16T03:30:00Z",
    unreadMessages: 3,
    whoSentLastMessage: "Mike",
  },
  {
    id: "",
    posts: [""],
    username: "Sophia",
    imageUrl: require("../assets/images/avatars/03.png"),
    message: "Let's grab lunch tomorrow! 🍔🥤",
    timestamp: "2024-07-15T13:15:00Z",
    unreadMessages: 0,
    whoSentLastMessage: "you",
  },
  {
    id: "",
    posts: [""],
    username: "Bertha",
    imageUrl: require("../assets/images/avatars/05.png"),
    message: "Just finished the workout 💪🏽🏋️‍♂️",
    timestamp: "2024-07-16T07:00:00Z",
    unreadMessages: 0,
    whoSentLastMessage: "you",
  },
  {
    id: "",
    posts: [""],
    username: "Emma",
    imageUrl: require("../assets/images/avatars/01.png"),
    message: "Happy Birthday! 🎉🎂🎈",
    timestamp: "2024-07-15T10:45:00Z",
    unreadMessages: 0,
    whoSentLastMessage: "Emma",
  },
  {
    id: "",
    posts: [""],
    username: "Alex",
    imageUrl: require("../assets/images/avatars/03.png"),
    message: "Let's play some games tonight! 🎮🕹️",
    timestamp: "2024-07-16T18:20:00Z",
    unreadMessages: 1,
    whoSentLastMessage: "Alex",
  },
  {
    id: "",
    posts: [""],
    username: "Isabella",
    imageUrl: require("../assets/images/avatars/05.png"),
    message: "Can you send me the report? 📄📧",
    timestamp: "2024-07-16T04:55:00Z",
    unreadMessages: 0,
    whoSentLastMessage: "Isabella",
  },
  {
    id: "",
    posts: [""],
    username: "Ableez",
    imageUrl: require("../assets/images/avatars/02.png"),
    message: "Hey whatsup bro🥂🥂✌🏽",
    timestamp: "2024-07-16T08:00:00Z",
    unreadMessages: 0,
    whoSentLastMessage: "you",
  },
  {
    id: "",
    posts: [""],
    username: "Laura",
    imageUrl: require("../assets/images/avatars/01.png"),
    message: "Are you coming over tonight?🌚",
    timestamp: "2024-07-15T20:30:00Z",
    unreadMessages: 0,
    whoSentLastMessage: "you",
  },
  {
    id: "",
    posts: [""],
    username: "Mike",
    imageUrl: require("../assets/images/avatars/02.png"),
    message: "Check out this cool new app! 😎📱",
    timestamp: "2024-07-16T03:30:00Z",
    unreadMessages: 0,
    whoSentLastMessage: "Mike",
  },
  {
    id: "",
    posts: [""],
    username: "Sophia",
    imageUrl: require("../assets/images/avatars/01.png"),
    message: "Let's grab lunch tomorrow! 🍔🥤",
    timestamp: "2024-07-15T13:15:00Z",
    unreadMessages: 0,
    whoSentLastMessage: "Sophia",
  },
  {
    id: "",
    posts: [""],
    username: "John",
    imageUrl: require("../assets/images/avatars/02.png"),
    message: "Just finished the workout 💪🏽🏋️‍♂️",
    timestamp: "2024-07-16T07:00:00Z",
    unreadMessages: 1,
    whoSentLastMessage: "John",
  },
  {
    id: "",
    posts: [""],
    username: "Emma",
    imageUrl: require("../assets/images/avatars/01.png"),
    message: "Happy Birthday! 🎉🎂🎈",
    timestamp: "2024-07-15T10:45:00Z",
    unreadMessages: 0,
    whoSentLastMessage: "Emma",
  },
  {
    id: "",
    posts: [""],
    username: "Alex",
    imageUrl: require("../assets/images/avatars/02.png"),
    message: "Let's play some games tonight! 🎮🕹️",
    timestamp: "2024-07-16T18:20:00Z",
    unreadMessages: 1,
    whoSentLastMessage: "Alex",
  },
  {
    id: "",
    posts: ["", ""],
    username: "Isabella",
    imageUrl: require("../assets/images/avatars/01.png"),
    message: "Can you send me the report? 📄📧",
    timestamp: "2024-07-16T04:55:00Z",
    unreadMessages: 3,
    whoSentLastMessage: "Isabella",
  },
];
