export const currentUser = {
  id: "user123",
  username: "ableez",
  email: "ableez@example.com",
  fullName: "Abdullahi Ahmed",
  bio: "Photography enthusiast",
  followers: ["user002", "user004"],
  following: ["user003", "user005"],
  posts: ["post123", "post456"],
  chats: ["chat123"],
  stories: ["story123"],
  reels: ["reel123"],
  profilePicture: require("../assets/images/avatars/02.png"),
  unreadMessages: 3,
};
